package pluginforge

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"axiom.local/agent/internal/pluginmanifest"
)

const (
	ShapeHybrid    = "hybrid"
	ShapeAgentTool = "agent-tool"
	ShapeUI        = "ui"
	ShapeService   = "service"
	ShapeSkill     = "skill"
)

func normalizeShape(shape string) string {
	switch strings.ToLower(strings.TrimSpace(shape)) {
	case ShapeAgentTool, ShapeUI, ShapeService, ShapeSkill, ShapeHybrid:
		return strings.ToLower(strings.TrimSpace(shape))
	default:
		return ShapeHybrid
	}
}

func projectShape(spec json.RawMessage) string {
	var value struct {
		Shape string `json:"shape"`
	}
	_ = json.Unmarshal(spec, &value)
	return normalizeShape(value.Shape)
}

func acceptanceForShape(shape string) []string {
	checks := []string{"manifest validates", "release digest is deterministic", "permissions are release-bound"}
	switch normalizeShape(shape) {
	case ShapeUI:
		return append(checks, "frontend loads in a strict sandbox")
	case ShapeSkill:
		return append(checks, "skill instructions are lazily discoverable")
	case ShapeService:
		return append(checks, "backend service compiles and passes tests")
	case ShapeAgentTool:
		return append(checks, "tool output matches its schema")
	default:
		return append(checks, "backend compiles and passes tests", "frontend loads in a strict sandbox", "tool output matches its schema")
	}
}

func referenceManifestV2(p Project, shape string) pluginmanifest.Manifest {
	shape = normalizeShape(shape)
	id := "workspace." + p.Slug
	manifest := pluginmanifest.Manifest{
		SpecVersion: pluginmanifest.SpecV2,
		ID:          id,
		Name:        p.Name,
		Version:     "0.2." + time.Now().UTC().Format("20060102150405"),
		Description: p.Description,
		Upgrade:     pluginmanifest.Upgrade{Strategy: "drain", PinActiveCalls: true, StateVersion: 1},
	}
	if shape == ShapeHybrid || shape == ShapeAgentTool || shape == ShapeService {
		manifest.Runtime = &pluginmanifest.Runtime{Backend: &pluginmanifest.Backend{Artifact: "backend/plugin.exe", Protocol: "axiom.rpc/v2", ShutdownMillis: 10000}}
	}
	if shape == ShapeHybrid || shape == ShapeUI {
		manifest.UI = &pluginmanifest.UI{Entry: "frontend/index.html", Assets: "frontend/**", Slots: []string{"workspace.main", "plugins.preview"}, Sandbox: "strict"}
	}
	if shape == ShapeHybrid || shape == ShapeAgentTool {
		manifest.Exports.Tools = []pluginmanifest.ToolExport{{
			ID: id + ".scan", Summary: "Scan workspace TODO and FIXME markers", Tags: []string{"workspace", "inspection"},
			Visibility: "discoverable", Risk: "workspace-readonly", Executor: pluginmanifest.Executor{Kind: "backend", Target: "capability.invoke"},
			InputSchema:  json.RawMessage(`{"type":"object","properties":{"root":{"type":"string"}},"additionalProperties":false}`),
			OutputSchema: json.RawMessage(`{"type":"object","required":["count","items"],"properties":{"count":{"type":"integer"},"items":{"type":"array"}}}`),
		}}
		manifest.Permissions.Filesystem.Read = []string{"${workspace}"}
	}
	if shape == ShapeService {
		manifest.Exports.Services = []pluginmanifest.ServiceExport{{ID: id + ".index", Contract: "axiom.workspace-index/v1", Handler: "service.call"}}
	}
	if shape == ShapeSkill {
		manifest.Exports.Skills = []pluginmanifest.SkillExport{{ID: id + ".guide", Summary: p.Description, Visibility: "discoverable", Entry: "skills/guide/SKILL.md"}}
	}
	return manifest
}

func writeProjectV2(p Project, manifest pluginmanifest.Manifest, shape string) error {
	if err := os.MkdirAll(p.SourceDir, 0o700); err != nil {
		return err
	}
	files := map[string][]byte{}
	manifestRaw, _ := json.MarshalIndent(manifest, "", "  ")
	files[filepath.Join(p.SourceDir, "plugin.json")] = manifestRaw
	files[filepath.Join(p.SourceDir, "README.md")] = []byte("# " + p.Name + "\n\n" + p.Description + "\n\nGenerated by Axiom Plugin Forge as a " + shape + " plugin.\n")
	if manifest.Runtime != nil {
		backendDir := filepath.Join(p.SourceDir, "backend")
		if err := os.MkdirAll(backendDir, 0o700); err != nil {
			return err
		}
		files[filepath.Join(backendDir, "go.mod")] = []byte("module axiom.generated/" + p.Slug + "\n\ngo 1.27.0\n")
		files[filepath.Join(backendDir, "main.go")] = []byte(referenceBrokeredBackendSource)
		files[filepath.Join(backendDir, "main_test.go")] = []byte(referenceBackendTest)
	}
	if manifest.UI != nil {
		frontendDir := filepath.Join(p.SourceDir, "frontend")
		if err := os.MkdirAll(frontendDir, 0o700); err != nil {
			return err
		}
		frontend := referenceFrontendSource
		if shape == ShapeUI {
			frontend = referenceStaticFrontendSource
		}
		files[filepath.Join(frontendDir, "index.html")] = []byte(frontend)
	}
	if len(manifest.Exports.Skills) > 0 {
		skillDir := filepath.Join(p.SourceDir, "skills", "guide")
		if err := os.MkdirAll(skillDir, 0o700); err != nil {
			return err
		}
		files[filepath.Join(skillDir, "SKILL.md")] = []byte("---\nname: " + manifest.Exports.Skills[0].ID + "\ndescription: " + p.Description + "\n---\n\n# Guide\n\nUse this skill only when the request matches the description. Inspect the workspace narrowly and return evidence with file paths.\n")
	}
	for path, contents := range files {
		if err := os.WriteFile(path, contents, 0o600); err != nil {
			return err
		}
	}
	return nil
}

func referenceManifest(p Project) Manifest {
	objectSchema := json.RawMessage(`{"type":"object","properties":{"root":{"type":"string"}},"additionalProperties":false}`)
	outputSchema := json.RawMessage(`{"type":"object","required":["count","items"],"properties":{"count":{"type":"integer"},"items":{"type":"array"}}}`)
	return Manifest{ID: "workspace." + p.Slug, Name: p.Name, Version: "0.1." + time.Now().UTC().Format("20060102150405"), APIVersion: "axiom.plugin/v1", Description: p.Description,
		Backend:      BackendEntry{Artifact: "backend/plugin.exe", Protocol: "axiom.rpc/v1", ShutdownMillis: 10000},
		Frontend:     FrontendEntry{Entry: "frontend/index.html", Slots: []string{"workspace.main", "plugins.preview"}},
		Capabilities: []Capability{{ID: "workspace." + p.Slug + ".scan", Summary: "Scan workspace TODO and FIXME markers", Risk: "workspace-readonly", InputSchema: objectSchema, OutputSchema: outputSchema}},
		Permissions:  PermissionSet{WorkspaceRead: true, PluginDataWrite: true}, Upgrade: UpgradePolicy{Strategy: "drain", PinActiveRuns: true, StateVersion: 1}}
}

func writeProject(p Project, manifest Manifest) error {
	backendDir := filepath.Join(p.SourceDir, "backend")
	frontendDir := filepath.Join(p.SourceDir, "frontend")
	if err := os.MkdirAll(backendDir, 0o700); err != nil {
		return err
	}
	if err := os.MkdirAll(frontendDir, 0o700); err != nil {
		return err
	}
	manifestRaw, _ := json.MarshalIndent(manifest, "", "  ")
	files := map[string][]byte{
		filepath.Join(p.SourceDir, "plugin.json"): manifestRaw,
		filepath.Join(backendDir, "go.mod"):       []byte("module axiom.generated/" + p.Slug + "\n\ngo 1.27.0\n"),
		filepath.Join(backendDir, "main.go"):      []byte(referenceBackendSource),
		filepath.Join(backendDir, "main_test.go"): []byte(referenceBackendTest),
		filepath.Join(frontendDir, "index.html"):  []byte(referenceFrontendSource),
		filepath.Join(p.SourceDir, "README.md"):   []byte("# " + p.Name + "\n\n" + p.Description + "\n\nGenerated by Axiom Plugin Forge.\n"),
	}
	for path, contents := range files {
		if err := os.WriteFile(path, contents, 0o600); err != nil {
			return err
		}
	}
	return nil
}

func commitGeneratedProject(dir string) {
	if _, err := os.Stat(filepath.Join(dir, ".git")); os.IsNotExist(err) {
		runGit(dir, "init", "-b", "main")
		runGit(dir, "config", "user.name", "Axiom Plugin Forge")
		runGit(dir, "config", "user.email", "forge@axiom.local")
	}
	runGit(dir, "add", ".")
	runGit(dir, "commit", "-m", "feat: generate initial plugin")
}
func commitSourceChange(dir, path string) {
	runGit(dir, "add", "--", path)
	runGit(dir, "commit", "-m", "feat: update "+path)
}
func runGit(dir string, args ...string) {
	command := exec.Command("git", args...)
	command.Dir = dir
	_ = command.Run()
}

const referenceBrokeredBackendSource = `package main

import (
 "bufio"
 "encoding/json"
 "fmt"
 "os"
 "path"
 "strings"
)

type request struct { ID string ` + "`json:\"id\"`" + `; Method string ` + "`json:\"method\"`" + `; Params json.RawMessage ` + "`json:\"params,omitempty\"`" + ` }
type response struct { ID string ` + "`json:\"id\"`" + `; Result any ` + "`json:\"result,omitempty\"`" + `; Error string ` + "`json:\"error,omitempty\"`" + ` }
type wireResponse struct { ID string ` + "`json:\"id\"`" + `; Result json.RawMessage ` + "`json:\"result\"`" + `; Error string ` + "`json:\"error\"`" + ` }
type todo struct { File string ` + "`json:\"file\"`" + `; Line int ` + "`json:\"line\"`" + `; Text string ` + "`json:\"text\"`" + `; Kind string ` + "`json:\"kind\"`" + ` }
type dirEntry struct { Name string ` + "`json:\"name\"`" + `; Directory bool ` + "`json:\"directory\"`" + `; Size int64 ` + "`json:\"size\"`" + ` }

func main() {
 scanner:=bufio.NewScanner(os.Stdin);scanner.Buffer(make([]byte,64<<10),1<<20)
 encoder:=json.NewEncoder(os.Stdout)
 for scanner.Scan(){
  var req request
  if err:=json.Unmarshal(scanner.Bytes(),&req);err!=nil{_ = encoder.Encode(response{Error:err.Error()});continue}
  result,err:=handle(req,scanner,encoder);out:=response{ID:req.ID,Result:result}
  if err!=nil{out.Result=nil;out.Error=err.Error()};_ = encoder.Encode(out)
  if req.Method=="plugin.shutdown"{return}
 }
}

func handle(req request,scanner *bufio.Scanner,encoder *json.Encoder)(any,error){
 switch req.Method{
 case "plugin.hello":return map[string]any{"protocol":"axiom.rpc/v2","status":"ready"},nil
 case "plugin.health":return map[string]any{"status":"healthy","resources":"host-brokered"},nil
 case "capabilities.list":return []string{"workspace.scan"},nil
 case "plugin.shutdown":return map[string]any{"status":"stopping"},nil
 case "ui.call":
  var input struct{Operation string ` + "`json:\"operation\"`" + `};if err:=json.Unmarshal(req.Params,&input);err!=nil{return nil,err};if input.Operation!="scan"{return nil,fmt.Errorf("unknown UI operation %s",input.Operation)}
  items,err:=scanTodos(scanner,encoder);return map[string]any{"count":len(items),"items":items},err
 case "service.call":
  var input struct{ServiceID string ` + "`json:\"_axiomServiceId\"`" + `; Principal string ` + "`json:\"principal\"`" + `; CallerPluginID string ` + "`json:\"callerPluginId\"`" + `; Input any ` + "`json:\"input\"`" + `};if err:=json.Unmarshal(req.Params,&input);err!=nil{return nil,err}
  return map[string]any{"serviceId":input.ServiceID,"principal":input.Principal,"callerPluginId":input.CallerPluginID,"input":input.Input,"ready":true},nil
 case "capability.invoke":items,err:=scanTodos(scanner,encoder);return map[string]any{"count":len(items),"items":items},err
 default:return nil,fmt.Errorf("unknown method %s",req.Method)
 }
}

func brokerCall(scanner *bufio.Scanner,encoder *json.Encoder,id,method string,input any,output any)error{
 raw,_:=json.Marshal(input);if err:=encoder.Encode(request{ID:id,Method:method,Params:raw});err!=nil{return err}
 if !scanner.Scan(){return fmt.Errorf("host broker closed")};var result wireResponse;if err:=json.Unmarshal(scanner.Bytes(),&result);err!=nil{return err};if result.ID!=id{return fmt.Errorf("host broker response mismatch")};if result.Error!=""{return fmt.Errorf("%s",result.Error)};return json.Unmarshal(result.Result,output)
}

func scanTodos(host *bufio.Scanner,encoder *json.Encoder)([]todo,error){
 result:=[]todo{};requestID:=0
 var walk func(string)error
 walk=func(directory string)error{
  requestID++;var listing struct{Entries []dirEntry ` + "`json:\"entries\"`" + `};if err:=brokerCall(host,encoder,fmt.Sprintf("fs_%d",requestID),"host.fs.list",map[string]any{"scope":"${workspace}","path":directory},&listing);err!=nil{return err}
  for _,entry:=range listing.Entries{relative:=entry.Name;if directory!="."{relative=path.Join(directory,entry.Name)};if entry.Directory{if !ignoredDir(entry.Name){if err:=walk(relative);err!=nil{return err}};continue};if entry.Size>1<<20||!textExtension(path.Ext(relative)){continue}
   requestID++;var file struct{Content string ` + "`json:\"content\"`" + `};if err:=brokerCall(host,encoder,fmt.Sprintf("fs_%d",requestID),"host.fs.read",map[string]any{"scope":"${workspace}","path":relative},&file);err!=nil{continue};scanner:=bufio.NewScanner(strings.NewReader(file.Content));line:=0
   for scanner.Scan(){line++;text:=scanner.Text();upper:=strings.ToUpper(text);kind:="";if strings.Contains(upper,"TODO"){kind="TODO"}else if strings.Contains(upper,"FIXME"){kind="FIXME"};if kind!=""{result=append(result,todo{File:relative,Line:line,Text:strings.TrimSpace(text),Kind:kind});if len(result)>=500{return nil}}}
  };return nil
 }
 if err:=walk(".");err!=nil{return nil,err};return result,nil
}
func textExtension(extension string)bool{switch strings.ToLower(extension){case ".go",".ts",".tsx",".js",".md",".py",".rs":return true};return false}
func ignoredDir(name string)bool{switch strings.ToLower(name){case ".git","node_modules","data","dist",".next",".npm-cache","plugin-store","work":return true};return false}
`

const referenceBackendSource = `package main

import (
 "bufio"
 "encoding/json"
 "fmt"
 "os"
 "path/filepath"
 "strings"
)

type request struct { ID string; Method string; Params json.RawMessage }
type response struct { ID string ` + "`json:\"id\"`" + `; Result any ` + "`json:\"result,omitempty\"`" + `; Error string ` + "`json:\"error,omitempty\"`" + ` }
type todo struct { File string ` + "`json:\"file\"`" + `; Line int ` + "`json:\"line\"`" + `; Text string ` + "`json:\"text\"`" + `; Kind string ` + "`json:\"kind\"`" + ` }

func main() {
 scanner := bufio.NewScanner(os.Stdin)
 encoder := json.NewEncoder(os.Stdout)
 for scanner.Scan() {
  var req request
  if err := json.Unmarshal(scanner.Bytes(), &req); err != nil { _ = encoder.Encode(response{Error:err.Error()}); continue }
  result, err := handle(req)
  out := response{ID:req.ID,Result:result}
  if err != nil { out.Result=nil; out.Error=err.Error() }
  _ = encoder.Encode(out)
  if req.Method == "plugin.shutdown" { return }
 }
}

func handle(req request) (any,error) {
 switch req.Method {
 case "plugin.hello": return map[string]any{"protocol":"axiom.rpc/v1","status":"ready"},nil
 case "plugin.health": return map[string]any{"status":"healthy"},nil
 case "capabilities.list": return []string{"workspace.scan"},nil
 case "plugin.shutdown": return map[string]any{"status":"stopping"},nil
 case "ui.call":
  var input struct { Operation string ` + "`json:\"operation\"`" + `; Root string ` + "`json:\"root\"`" + ` }
  if err:=json.Unmarshal(req.Params,&input);err!=nil{return nil,err}
  if input.Operation!="scan"{return nil,fmt.Errorf("unknown UI operation %s",input.Operation)}
  if input.Root==""{return nil,fmt.Errorf("workspace access is not granted")}
  items,err:=scanTodos(input.Root);if err!=nil{return nil,err}
  return map[string]any{"count":len(items),"items":items},nil
 case "capability.invoke":
  var input struct { Root string ` + "`json:\"root\"`" + ` }
  if err:=json.Unmarshal(req.Params,&input);err!=nil{return nil,err}
  if input.Root==""{return nil,fmt.Errorf("root is required")}
  items,err:=scanTodos(input.Root);if err!=nil{return nil,err}
  return map[string]any{"count":len(items),"items":items},nil
 default:return nil,fmt.Errorf("unknown method %s",req.Method)
 }
}

func scanTodos(root string)([]todo,error){
 result:=[]todo{}
 err:=filepath.WalkDir(root,func(path string,entry os.DirEntry,walkErr error)error{
  if walkErr!=nil{return nil}
  if entry.IsDir(){if ignoredDir(entry.Name())&&path!=root{return filepath.SkipDir};return nil}
  info,err:=entry.Info();if err!=nil||info.Size()>2<<20{return nil}
  ext:=strings.ToLower(filepath.Ext(path));if ext!=".go"&&ext!=".ts"&&ext!=".tsx"&&ext!=".js"&&ext!=".md"&&ext!=".py"&&ext!=".rs"{return nil}
  file,err:=os.Open(path);if err!=nil{return nil};defer file.Close();scanner:=bufio.NewScanner(file);line:=0
  for scanner.Scan(){line++;text:=scanner.Text();upper:=strings.ToUpper(text);kind:="";if strings.Contains(upper,"TODO"){kind="TODO"}else if strings.Contains(upper,"FIXME"){kind="FIXME"};if kind!=""{relative,_:=filepath.Rel(root,path);result=append(result,todo{File:filepath.ToSlash(relative),Line:line,Text:strings.TrimSpace(text),Kind:kind});if len(result)>=500{return fmt.Errorf("limit reached")}}}
  return nil
 })
 if err!=nil&&err.Error()!="limit reached"{return nil,err};return result,nil
}
func ignoredDir(name string)bool{switch strings.ToLower(name){case ".git","node_modules","data","dist",".next",".npm-cache","plugin-store":return true};return false}
`

const referenceBackendTest = `package main
import "testing"
func TestIgnoredDirectories(t *testing.T){for _,name:=range []string{".git","node_modules","data"}{if !ignoredDir(name){t.Fatalf("%s should be ignored",name)}};if ignoredDir("src"){t.Fatal("src must remain visible")}}
`

const referenceFrontendSource = `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>
:root{color-scheme:dark;font-family:ui-monospace,monospace;background:#0e1112;color:#e8ecea}*{box-sizing:border-box}body{margin:0;padding:24px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #293033;padding-bottom:16px}h1{font:600 18px system-ui;margin:0}button{border:0;background:#c8ff4f;color:#0a0c0d;padding:10px 15px;font-weight:700;cursor:pointer}.meta{font-size:10px;color:#7e898c;letter-spacing:.12em}.summary{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:18px 0}.card{border:1px solid #293033;padding:14px}.card b{display:block;font-size:26px;color:#c8ff4f}.item{border-top:1px solid #22282a;padding:10px 0;font-size:11px}.item span{color:#899296}.empty{color:#768083;padding:30px 0}.error{color:#ff875e}</style></head>
<body><header><div><div class="meta">AXIOM GENERATED PLUGIN</div><h1>Workspace TODO Inspector</h1></div><button id="scan">Scan workspace</button></header><div class="summary"><div class="card"><span class="meta">MARKERS</span><b id="count">—</b></div><div class="card"><span class="meta">RUNTIME</span><b>HOT</b></div></div><main id="result" class="empty">Run the capability to inspect this workspace.</main>
<script>var requestId=0;var pending={};document.getElementById('scan').onclick=function(){var id='ui_'+(++requestId);pending[id]=true;document.getElementById('result').textContent='Scanning…';parent.postMessage({type:'axiom.ui.call',id:id,operation:'scan',input:{}},'*')};addEventListener('message',function(event){var data=event.data||{};if(data.type!=='axiom.ui.result'||!pending[data.id])return;delete pending[data.id];var result=document.getElementById('result');if(data.error){result.className='error';result.textContent=data.error;return}var output=data.output||{};document.getElementById('count').textContent=output.count||0;result.className='';result.innerHTML='';(output.items||[]).slice(0,100).forEach(function(item){var row=document.createElement('div');row.className='item';row.textContent=item.kind+' · '+item.file+':'+item.line+' ';var span=document.createElement('span');span.textContent=item.text;row.appendChild(span);result.appendChild(row)});if(!output.count){result.className='empty';result.textContent='No TODO or FIXME markers found.'}});parent.postMessage({type:'axiom.ui.ready'},'*');</script></body></html>`

const referenceStaticFrontendSource = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>:root{color-scheme:dark;font-family:system-ui;background:#0e1112;color:#e8ecea}body{margin:0;padding:28px}.card{border:1px solid #293033;padding:24px}small{color:#c8ff4f;letter-spacing:.12em}h1{font-size:22px}p{color:#9aa4a6;line-height:1.6}</style></head><body><section class="card"><small>AXIOM UI EXTENSION</small><h1>Presentation surface active</h1><p>This plugin contributes a sandboxed UI only. It does not expose an Agent tool or start a backend process.</p></section><script>parent.postMessage({type:'axiom.ui.ready'},'*')</script></body></html>`
