package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

type attemptBudgetContextKey struct{}
type requestAuditContextKey struct{}

// RequestAudit contains a hash of the exact JSON request body generated by the
// selected provider adapter. The observer runs before the HTTP request is sent;
// returning an error prevents the call from leaving the process.
type RequestAudit struct {
	PayloadSHA256 string
	RequestBytes  int
}

// WithRequestAudit attaches a pre-send audit callback to a model call.
func WithRequestAudit(ctx context.Context, observer func(RequestAudit) error) context.Context {
	if observer == nil {
		return ctx
	}
	return context.WithValue(ctx, requestAuditContextKey{}, observer)
}

func requestAuditObserver(ctx context.Context) func(RequestAudit) error {
	observer, _ := ctx.Value(requestAuditContextKey{}).(func(RequestAudit) error)
	return observer
}

// EstimateInputTokens provides a conservative, provider-independent estimate
// for request budgeting. It intentionally counts non-ASCII runes as one token
// and JSON/tool syntax as input rather than relying on a model-specific tokenizer.
func EstimateInputTokens(messages []ChatMessage, tools []ToolDefinition) int {
	text := strings.Builder{}
	for _, message := range messages {
		text.WriteString(message.Role)
		text.WriteString(message.Content)
		text.WriteString(message.ToolCallID)
		for _, item := range message.ProviderItems {
			text.Write(item)
		}
		for _, call := range message.ToolCalls {
			text.WriteString(call.ID)
			text.WriteString(call.Function.Name)
			text.WriteString(call.Function.Arguments)
		}
	}
	for _, tool := range tools {
		text.WriteString(tool.Type)
		text.WriteString(tool.Function.Name)
		text.WriteString(tool.Function.Description)
		text.Write(tool.Function.Parameters)
	}
	ascii, nonASCII := 0, 0
	for _, r := range text.String() {
		if r <= 0x7f {
			ascii++
		} else {
			nonASCII++
		}
	}
	return (ascii+2)/3 + nonASCII + len(messages)*8 + len(tools)*16
}

// WithAttemptBudget limits the number of HTTP attempts used by one provider
// completion. It lets the Agent runtime reserve retry attempts inside its
// host-owned per-run model-call ceiling.
func WithAttemptBudget(ctx context.Context, attempts int) context.Context {
	if attempts < 1 {
		return ctx
	}
	return context.WithValue(ctx, attemptBudgetContextKey{}, attempts)
}

func attemptBudget(ctx context.Context) (int, bool) {
	value, ok := ctx.Value(attemptBudgetContextKey{}).(int)
	return value, ok
}

const (
	MaxCompletionAttempts = 3
	KindNewAPI            = "new-api"
	KindOneAPI            = "one-api"
	KindOpenAICompatible  = "openai-compatible"
	KindOpenAIResponses   = "openai-responses"
	KindAnthropicMessages = "anthropic-messages"
	KindDeepSeekChat      = "deepseek-chat"
	KindOllama            = "ollama"
	KindVLLM              = "vllm"
)

type SupportLevel string

const (
	SupportUnknown SupportLevel = "unknown"
	SupportNo      SupportLevel = "no"
	SupportYes     SupportLevel = "yes"
)

type ModelCapabilities struct {
	Tools             SupportLevel `json:"tools"`
	ParallelToolCalls SupportLevel `json:"parallelToolCalls"`
	Streaming         SupportLevel `json:"streaming"`
	Vision            SupportLevel `json:"vision"`
	StrictJSONSchema  SupportLevel `json:"strictJsonSchema"`
	ReasoningControl  SupportLevel `json:"reasoningControl"`
	PromptCaching     SupportLevel `json:"promptCaching"`
}

type KindDescriptor struct {
	Kind           string            `json:"kind"`
	Label          string            `json:"label"`
	Description    string            `json:"description"`
	DefaultBaseURL string            `json:"defaultBaseUrl"`
	Capabilities   ModelCapabilities `json:"capabilities"`
}

func Kinds() []KindDescriptor {
	return []KindDescriptor{
		{Kind: KindNewAPI, Label: "New-API / One-API", Description: "Universal open-source LLM router / gateway with unified OpenAI completions format.", DefaultBaseURL: "http://127.0.0.1:3000/v1", Capabilities: ModelCapabilities{Tools: SupportYes, ParallelToolCalls: SupportYes, Streaming: SupportYes, Vision: SupportYes, StrictJSONSchema: SupportYes, ReasoningControl: SupportYes, PromptCaching: SupportYes}},
		{Kind: KindOpenAIResponses, Label: "OpenAI Responses", Description: "OpenAI's Responses API with native function calls.", DefaultBaseURL: "https://api.openai.com/v1", Capabilities: ModelCapabilities{Tools: SupportYes, ParallelToolCalls: SupportYes, Streaming: SupportYes, Vision: SupportYes, StrictJSONSchema: SupportYes, ReasoningControl: SupportYes, PromptCaching: SupportYes}},
		{Kind: KindAnthropicMessages, Label: "Anthropic Messages", Description: "Anthropic Messages API with tool_use and tool_result blocks.", DefaultBaseURL: "https://api.anthropic.com/v1", Capabilities: ModelCapabilities{Tools: SupportYes, ParallelToolCalls: SupportYes, Streaming: SupportYes, Vision: SupportYes, StrictJSONSchema: SupportUnknown, ReasoningControl: SupportYes, PromptCaching: SupportYes}},
		{Kind: KindDeepSeekChat, Label: "DeepSeek Chat", Description: "DeepSeek's OpenAI-compatible chat API with conservative defaults.", DefaultBaseURL: "https://api.deepseek.com/v1", Capabilities: ModelCapabilities{Tools: SupportYes, ParallelToolCalls: SupportUnknown, Streaming: SupportYes, Vision: SupportNo, StrictJSONSchema: SupportUnknown, ReasoningControl: SupportUnknown, PromptCaching: SupportYes}},
		{Kind: KindOllama, Label: "Ollama", Description: "Local open-source models via Ollama (Llama, Qwen, DeepSeek).", DefaultBaseURL: "http://127.0.0.1:11434/v1", Capabilities: ModelCapabilities{Tools: SupportYes, ParallelToolCalls: SupportUnknown, Streaming: SupportYes, Vision: SupportYes, StrictJSONSchema: SupportUnknown, ReasoningControl: SupportUnknown, PromptCaching: SupportUnknown}},
		{Kind: KindVLLM, Label: "vLLM / LocalAI", Description: "High-throughput open-source LLM inference serving OpenAI-compatible endpoints.", DefaultBaseURL: "http://127.0.0.1:8000/v1", Capabilities: ModelCapabilities{Tools: SupportYes, ParallelToolCalls: SupportYes, Streaming: SupportYes, Vision: SupportUnknown, StrictJSONSchema: SupportUnknown, ReasoningControl: SupportUnknown, PromptCaching: SupportUnknown}},
		{Kind: KindOpenAICompatible, Label: "OpenAI-compatible", Description: "A custom endpoint implementing the Chat Completions wire format.", DefaultBaseURL: "http://127.0.0.1:8000/v1", Capabilities: ModelCapabilities{Tools: SupportUnknown, ParallelToolCalls: SupportUnknown, Streaming: SupportUnknown, Vision: SupportUnknown, StrictJSONSchema: SupportUnknown, ReasoningControl: SupportUnknown, PromptCaching: SupportUnknown}},
	}
}

func normalizeKind(value string) (string, bool) {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "", KindOpenAICompatible, "openai-chat", "openai-chat-completions":
		return KindOpenAICompatible, true
	case KindNewAPI, "newapi", KindOneAPI, "oneapi":
		return KindNewAPI, true
	case KindOpenAIResponses, "responses":
		return KindOpenAIResponses, true
	case KindAnthropicMessages, "anthropic":
		return KindAnthropicMessages, true
	case KindDeepSeekChat, "deepseek":
		return KindDeepSeekChat, true
	case KindOllama:
		return KindOllama, true
	case KindVLLM, "localai":
		return KindVLLM, true
	default:
		return "", false
	}
}

type ErrorClass string

const (
	ErrorAuthentication  ErrorClass = "authentication"
	ErrorRateLimit       ErrorClass = "rate_limit"
	ErrorUnavailable     ErrorClass = "unavailable"
	ErrorInvalidRequest  ErrorClass = "invalid_request"
	ErrorNotFound        ErrorClass = "not_found"
	ErrorContextOverflow ErrorClass = "context_overflow"
	ErrorUnsupported     ErrorClass = "unsupported"
	ErrorProtocol        ErrorClass = "protocol"
	ErrorCancelled       ErrorClass = "cancelled"
)

type ProviderError struct {
	Class      ErrorClass
	StatusCode int
	RetryAfter time.Duration
	Attempts   int
	SafeDetail string
	Cause      error
}

func (e *ProviderError) Error() string {
	if e.SafeDetail != "" {
		return e.SafeDetail
	}
	return fmt.Sprintf("provider request failed (%s)", e.Class)
}

func (e *ProviderError) Unwrap() error { return e.Cause }

type CompatibilityWarning struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// UnmarshalJSON accepts the standard JSON-string argument representation and
// the object form emitted by some nominally OpenAI-compatible providers.
func (f *ToolFunction) UnmarshalJSON(data []byte) error {
	f.normalizedObjectArguments = false
	var value struct {
		Name      string          `json:"name"`
		Arguments json.RawMessage `json:"arguments"`
	}
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	f.Name = value.Name
	if len(value.Arguments) == 0 || string(value.Arguments) == "null" {
		f.Arguments = "{}"
		return nil
	}
	if value.Arguments[0] == '"' {
		return json.Unmarshal(value.Arguments, &f.Arguments)
	}
	compact, err := json.Marshal(json.RawMessage(value.Arguments))
	if err != nil {
		return err
	}
	f.Arguments = string(compact)
	f.normalizedObjectArguments = true
	return nil
}
